<?php


// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/


$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://smsapi.free-mobile.fr/sendmsg?user=14674807&pass=LT8SgPujYIYJ9E&msg=Mise à jour faite');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);


?>